#pragma once

#include <Foundation/Basics.h>

#if NS_ENABLED(NS_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_JVDSDK_LIB
#    define NS_JVDSDK_DLL NS_DECL_EXPORT
#    define NS_JVDSDK_DLL_FRIEND NS_DECL_EXPORT_FRIEND
#  else
#    define NS_JVDSDK_DLL NS_DECL_IMPORT
#    define NS_JVDSDK_DLL_FRIEND NS_DECL_IMPORT_FRIEND
#  endif
#else
#  define NS_JVDSDK_DLL
#  define NS_JVDSDK_DLL_FRIEND
#endif
